name: "Terraform PR Plan"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Terraform Plan (simulate=true)
        run: terraform -chdir=infra plan -input=false -var="simulate=true" -out=plan.tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/plan.tfplan
