name: "Terraform Manual Apply"

on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  apply:
    name: terraform-apply
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Terraform Apply (simulate=false)
        run: terraform -chdir=infra apply -input=false -auto-approve -var="simulate=false"
